/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.RegionController;
import java.awt.event.KeyEvent;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Region;

/**
 *
 * @author Laila
 */
public class RegionView extends javax.swing.JInternalFrame {

    private RegionController regionController = null;
    /**
     * Creates new form RegionView
     */
    public RegionView() {
        initComponents();
        regionController = new RegionController();
        loadData(regionController.binding());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputStrSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputId = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRegion = new javax.swing.JTable();
        show_validation_id = new javax.swing.JLabel();
        show_validation_name = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Region");
        setToolTipText(" ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(40, 20));

        inputStrSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStrSearchActionPerformed(evt);
            }
        });
        inputStrSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputStrSearchKeyPressed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Detail Region");

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });
        inputId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputIdKeyPressed(evt);
            }
        });

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        inputName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNameKeyPressed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tbRegion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRegionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRegion);

        show_validation_id.setForeground(new java.awt.Color(255, 0, 0));
        show_validation_id.setText(" ");

        show_validation_name.setForeground(new java.awt.Color(255, 0, 0));
        show_validation_name.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(show_validation_id)
                                    .addComponent(show_validation_name))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputStrSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputStrSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_validation_id))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_validation_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(22, 22, 22))
        );

        getAccessibleContext().setAccessibleName("vwRegion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputStrSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStrSearchActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_inputStrSearchActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

//menampilkan confirm dialog sebelum menyimpan data
int YesOrNo = JOptionPane.showConfirmDialog(null, "Anda yakin akan menyimpan data ini?", "Simpan data", JOptionPane.YES_NO_OPTION);
String id = inputId.getText();
String name = inputName.getText();
if (YesOrNo ==0){


        String message = regionController.ctr_controller_save(id, name);
        JOptionPane.showMessageDialog(this, message, "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        loadData(regionController.binding());

}
else if (YesOrNo ==1 ){
       
    
        // TODO add your handling code here:
}


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

//menampilkan confirm dialog sebelum update data
int YesOrNo = JOptionPane.showConfirmDialog(null, "Anda yakin akan menyimpan data ini?", "Simpan data", JOptionPane.YES_NO_OPTION);
String id = inputId.getText();
String name = inputName.getText();
if (YesOrNo ==0){


        String message = regionController.ctr_controller_update(id, name);
        JOptionPane.showMessageDialog(this, message, "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        loadData(regionController.binding());

}
else if (YesOrNo ==1 ){
       
    

}


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

//menampilkan confirm dialog sebelum menghapus data        
int YesOrNo = JOptionPane.showConfirmDialog(null, "Anda yakin akan menyimpan data ini?", "Simpan data", JOptionPane.YES_NO_OPTION);
String id = inputId.getText();
String name = inputName.getText();
if (YesOrNo ==0){


        String message = regionController.ctr_controller_delete(id);
        JOptionPane.showMessageDialog(this, message, "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
        loadData(regionController.binding());

}
else if (YesOrNo ==1 ){
       
    
        // TODO add your handling code here:
}

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
String keyword = "%"+inputStrSearch.getText()+"%";
//regionController.updatesearch(keyword);

loadData(regionController.ctr_controller_search(keyword));


        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRegionMouseClicked

//mengisi kolom id, name dengan mengambil dari isi row 0 dan 1 dari baris tabel tbRegion
int row =tbRegion.getSelectedRow();
String id =tbRegion.getValueAt(row, 0).toString();
String name =tbRegion.getValueAt(row, 1).toString();
inputId.setText(id);
inputName.setText(name);
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRegionMouseClicked

    private void inputIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIdKeyPressed

//membuat agar input hanya boleh huruf        
char c= evt.getKeyChar();
if(Character.isLetter(c)){
    show_validation_id.setText("Tolong masukkan angka");
}
else if(Character.isDigit(c)){
    show_validation_id.setText("");
}
else{
    show_validation_id.setText("Tolong masukkan angka");
    
}
//        try {
//            int id= Integer.parseInt(inputId.getText());
//            show_validation_id.setText("");
//            
//        } catch (Exception e) {
//        show_validation_id.setText("Tolong masukkan id dengan angka, misal :1,2.");
//        
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdKeyPressed

    private void inputNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameKeyPressed

        /*if(!(Character.isLetter(evt.getKeyChar()))){
    evt.consume();
}
        try {*/
        //        } catch (Exception e) {
//        show_validation_name.setText("Tolong masukkan id dengan angka, misal :1,2.");

        
//membuat agar input hanya boleh huruf

char name= evt.getKeyChar();

            if(!(Character.isAlphabetic(name))){
               show_validation_name.setText("Tolong masukkan huruf");               
            }
            
else if(Character.isAlphabetic(name) ){
        show_validation_name.setText("");
//        }
            }        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameKeyPressed

    private void inputStrSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputStrSearchKeyPressed
        // TODO add your handling code here:

//membuat agar saat kita mengetikkan sesuatu pada kolom search, tanpa mengklik tombol search, 
//kita tetap bisa mencari data tersebut dengan menekan enter
if(evt.getKeyCode()== KeyEvent.VK_ENTER);
String keyword = "%"+inputStrSearch.getText()+"%";
loadData(regionController.ctr_controller_search(keyword));
    }//GEN-LAST:event_inputStrSearchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputStrSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel show_validation_id;
    private javax.swing.JLabel show_validation_name;
    private javax.swing.JTable tbRegion;
    // End of variables declaration//GEN-END:variables

    private void loadData(List<Region> regions){
        String header[] = {"Id", "Name"};
        String [][] data = new String[regions.size()][2];
//    String data[] = new String[regions.size()][2];
        for (int i = 0; i < data.length; i++) {
//            String string = data[i];
data[i][0]= regions.get(i).getId()+"";
data[i][1]= regions.get(i).getName();
//            
        }
        DefaultTableModel defaultTableModel = new DefaultTableModel(data, header);
       tbRegion.setModel(defaultTableModel);
}
}